In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10,3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [6]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [7]:
a[2]

np.int64(3)

In [8]:
a[2] = 5
a

array([1, 2, 5, 4, 5, 6])

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [11]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

Multi Dimensional Arrays

In [12]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
n = np.array([
    [1,2,3],
    [2,3,4],
    [4,5,6]
])

In [14]:
n[0, 1]

np.int64(2)

In [15]:
n[:, 2]

array([3, 4, 6])

In [16]:
n[1, :]

array([2, 3, 4])

Generate Random Numbers

In [17]:
np.random.seed(2)
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [18]:
np.random.seed(2)
np.random.randn(5,2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [19]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=[5,3])

array([[40, 15, 72],
       [22, 43, 82],
       [75,  7, 34],
       [49, 95, 75],
       [85, 47, 63]])

Element wise Operation

In [20]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [21]:
a + 1

array([1, 2, 3, 4, 5])

In [22]:
b = (10 + (a*2)) ** 2 /100

In [23]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [24]:
a + b *100

array([100., 145., 198., 259., 328.])

Comparision Operators

In [25]:
a

array([0, 1, 2, 3, 4])

In [26]:
a >= 2

array([False, False,  True,  True,  True])

In [27]:
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [28]:
a > b

array([False, False,  True,  True,  True])

In [29]:
b < a

array([False, False,  True,  True,  True])

In [30]:
a[a>b]

array([2, 3, 4])

In [31]:
b[b<a]

array([1.96, 2.56, 3.24])

Summarizing Options

In [32]:
a

array([0, 1, 2, 3, 4])

In [33]:
a.mean()

np.float64(2.0)

In [34]:
a.std()

np.float64(1.4142135623730951)

In [35]:
n

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [36]:
n.sum()

np.int64(30)

In [37]:
n.min()

np.int64(1)

In [38]:
n.max()

np.int64(6)

Multiplication

In [39]:
u = np.array([2,4,5,6])

In [40]:
2 * u

array([ 4,  8, 10, 12])

In [41]:
u

array([2, 4, 5, 6])

In [42]:
v = np.array([3,5,5,6])

In [43]:
v.shape[0]

4

In [44]:
u.shape[0]

4

In [45]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]

    result = 0.0
    n = u.shape[0]

    for i in range(n):
        result = result + u[i] * v[i]

    return result

In [46]:
vector_vector_multiplication(u, v)

np.float64(87.0)

In [47]:
u.dot(v)

np.int64(87)

In [48]:
U = np.array([
    [1,2,3,4],
    [4,5,6,7],
    [7,8,9,10]
])

In [49]:
U.shape[1] == v.shape[0]

True

In [50]:
U.shape

(3, 4)

In [51]:
U.shape[0]

3

In [52]:
U.shape[1]

4

In [53]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range (num_rows):
        result[i] = vector_vector_multiplication(U[i], v)

    return result

In [54]:
matrix_vector_multiplication(U, v)

array([ 52., 109., 166.])

In [55]:
U.dot(v)

array([ 52, 109, 166])

In [56]:
V = np.array([
    [1,2,3,4],
    [2,3,4,5],
    [4,5,6,7],
    [7,8,9,10]
])

In [57]:
V.shape

(4, 4)

In [58]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range (num_cols):
        vi = V[:,i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi

    return result

In [59]:
matrix_matrix_multiplication(U, V)

array([[ 45.,  55.,  65.,  75.],
       [ 87., 109., 131., 153.],
       [129., 163., 197., 231.]])

In [60]:
U.dot(V)

array([[ 45,  55,  65,  75],
       [ 87, 109, 131, 153],
       [129, 163, 197, 231]])

Identity Matrix

In [61]:
I = np.eye(4)

In [62]:
V.dot(I)

array([[ 1.,  2.,  3.,  4.],
       [ 2.,  3.,  4.,  5.],
       [ 4.,  5.,  6.,  7.],
       [ 7.,  8.,  9., 10.]])

Inverse

In [63]:
b = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1]
])

In [64]:
Vs = b[[0,1,2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [65]:
Vs_inverse = np.linalg.inv(Vs)
Vs_inverse

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [66]:
Vs_inverse.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
import pandas as pd

DataFrames

In [68]:
data = [
    ['Nissan', 'Stanza', 1991, 138, 4, 'MANUAL', 'sedan', 2000],
    ['Hyundai', 'Sonata', 2017, None, 4, 'AUTOMATIC', 'Sedan', 27150],
    ['Lotus', 'Elise', 2010, 218, 4, 'MANUAL', 'convertible', 54990],
    ['GMC', 'Acadia',  2017, 194, 4, 'AUTOMATIC', '4dr SUV', 34450],
    ['Nissan', 'Frontier', 2017, 261, 6, 'MANUAL', 'Pickup', 32340],
]

columns = [
    'Make', 'Model', 'Year', 'Engine HP', 'Engine Cylinders',
    'Transmission Type', 'Vehicle_Style', 'MSRP'
]

In [69]:
df = pd.DataFrame(data, columns=columns)
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [70]:
df.head()

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [71]:
df.head(n=2)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150

In [72]:
df.Make

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [73]:
df['Make']

0     Nissan
1    Hyundai
2      Lotus
3        GMC
4     Nissan
Name: Make, dtype: str

In [74]:
df['Engine HP']

0    138.0
1      NaN
2    218.0
3    194.0
4    261.0
Name: Engine HP, dtype: float64

In [75]:
df[['Make', 'Model', 'Engine HP']]

      Make     Model  Engine HP
0   Nissan    Stanza      138.0
1  Hyundai    Sonata        NaN
2    Lotus     Elise      218.0
3      GMC    Acadia      194.0
4   Nissan  Frontier      261.0

Index

In [76]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [77]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [78]:
df.loc[1]

Make                   Hyundai
Model                   Sonata
Year                      2017
Engine HP                  NaN
Engine Cylinders             4
Transmission Type    AUTOMATIC
Vehicle_Style            Sedan
MSRP                     27150
Name: 1, dtype: object

In [79]:
df.loc[[1, 2]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990

In [80]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [81]:
df.index = ['a', 'b', 'c', 'd', 'e']

In [82]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [83]:
df.loc['a']

Make                 Nissan
Model                Stanza
Year                   1991
Engine HP             138.0
Engine Cylinders          4
Transmission Type    MANUAL
Vehicle_Style         sedan
MSRP                   2000
Name: a, dtype: object

In [84]:
df.loc[['a', 'c']]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990

In [85]:
df.iloc[[1, 2, 4]]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [86]:
df.reset_index(drop = True)

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
0,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
1,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
2,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
3,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
4,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [87]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

Element Wise Operations

In [88]:
df['Engine HP']/100

a    1.38
b     NaN
c    2.18
d    1.94
e    2.61
Name: Engine HP, dtype: float64

In [89]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [90]:
df['Year'] > 2015

a    False
b     True
c    False
d     True
e     True
Name: Year, dtype: bool

In [91]:
df[
    df['Make'] == 'Nissan'
]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [92]:
df[
    (df['Make'] == 'Nissan') & (df['Year'] >= 2015)
]

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

String Operations

In [93]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [94]:
df['Vehicle_Style']

a          sedan
b          Sedan
c    convertible
d        4dr SUV
e         Pickup
Name: Vehicle_Style, dtype: str

In [95]:
df['Vehicle_Style'].str.lower()

a          sedan
b          sedan
c    convertible
d        4dr suv
e         pickup
Name: Vehicle_Style, dtype: str

In [96]:
df['Vehicle_Style'].str.replace(' ','_')

a          sedan
b          Sedan
c    convertible
d        4dr_SUV
e         Pickup
Name: Vehicle_Style, dtype: str

In [97]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,Sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr SUV,34450
e,Nissan,Frontier,2017,261.0,6,MANUAL,Pickup,32340

In [98]:
df['Vehicle_Style'] = df['Vehicle_Style'].str.replace(' ','_').str.lower()

In [99]:
df

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,Nissan,Stanza,1991,138.0,4,MANUAL,sedan,2000
b,Hyundai,Sonata,2017,NaN,4,AUTOMATIC,sedan,27150
c,Lotus,Elise,2010,218.0,4,MANUAL,convertible,54990
d,GMC,Acadia,2017,194.0,4,AUTOMATIC,4dr_suv,34450
e,Nissan,Frontier,2017,261.0,6,MANUAL,pickup,32340

Summarizing Operators

In [100]:
df.MSRP

a     2000
b    27150
c    54990
d    34450
e    32340
Name: MSRP, dtype: int64

In [101]:
df.MSRP.min()

np.int64(2000)

In [102]:
df.MSRP.max()

np.int64(54990)

In [103]:
df.MSRP.mean()

np.float64(30186.0)

In [104]:
df.MSRP.describe()

count        5.000000
mean     30186.000000
std      18985.044904
min       2000.000000
25%      27150.000000
50%      32340.000000
75%      34450.000000
max      54990.000000
Name: MSRP, dtype: float64

In [105]:
df.describe().round()

         Year  Engine HP  Engine Cylinders     MSRP
count     5.0        4.0               5.0      5.0
mean   2010.0      203.0               4.0  30186.0
std      11.0       51.0               1.0  18985.0
min    1991.0      138.0               4.0   2000.0
25%    2010.0      180.0               4.0  27150.0
50%    2017.0      206.0               4.0  32340.0
75%    2017.0      229.0               4.0  34450.0
max    2017.0      261.0               6.0  54990.0

In [106]:
df.Make.nunique()

4

In [107]:
df.isnull()

,Make,Model,Year,Engine HP,Engine Cylinders,Transmission Type,Vehicle_Style,MSRP
a,False,False,False,False,False,False,False,False
b,False,False,False,True,False,False,False,False
c,False,False,False,False,False,False,False,False
d,False,False,False,False,False,False,False,False
e,False,False,False,False,False,False,False,False

In [108]:
df.isnull().sum()

Make                 0
Model                0
Year                 0
Engine HP            1
Engine Cylinders     0
Transmission Type    0
Vehicle_Style        0
MSRP                 0
dtype: int64

Grouping

In [109]:
'''
SELECT 
    transimission_type,
    AVG(MSRP)
FROM 
    cars
GROUP BY 
    transmission_type
'''

'\nSELECT \n    transimission_type,\n    AVG(MSRP)\nFROM \n    cars\nGROUP BY \n    transmission_type\n'

In [110]:
df.groupby('Transmission Type').MSRP.max()

Transmission Type
AUTOMATIC    34450
MANUAL       54990
Name: MSRP, dtype: int64

In [111]:
df.MSRP.values

array([ 2000, 27150, 54990, 34450, 32340])

In [112]:
df.to_dict(orient='records')

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'sedan',
  'MSRP': 27150},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Engine Cylinders': 4,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr_suv',
  'MSRP': 34450},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Engine Cylinders': 6,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'pickup',
  'MSRP': 32340}]